import { AnimeModelProvider } from "@/animeModel";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./(views)/navbarView";
import { WeatherModelProvider } from "@/weatherModel";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <Navbar />
          <AnimeModelProvider>
            <WeatherModelProvider>{children}</WeatherModelProvider>
          </AnimeModelProvider>
        </main>
      </body>
    </html>
  );
}
