import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./(views)/navbarView";
import { AuthProvider } from "../authentication";
import Navbarr from "@/app/(presenters)/navbarPresenter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <main>
            <Navbarr />
            {children}
          </main>
        </body>
      </html>
    </AuthProvider>
  );
}
